"""add money splits, notifications and subscription tables

Catch-up revision. These seventeen tables have existed in every running
database for some time, but no migration ever created them: they were made by
`Base.metadata.create_all()` on startup and by migrate.py, so the migration
chain could only ever build 22 of the schema's 39 tables. That gap is invisible
while every database is already ahead of it, and total the moment you point the
project at a new one -- a new teammate, a test database, or the hosted
development database this revision was written for.

The DDL is autogenerated from the models as they stand, which is exactly what
those tables already are.

Every create is guarded by an existence check, because the databases this lands
on are precisely the ones that already have these tables.

Revision ID: 1863a55d8be8
Revises: e7a4c1b90d26
Create Date: 2026-09-10 16:53:07.031475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1863a55d8be8'
down_revision: Union[str, Sequence[str], None] = 'e7a4c1b90d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('notification_preferences'):
        op.create_table('notification_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('in_app_enabled', sa.Boolean(), nullable=True),
        sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
        sa.Column('split_enabled', sa.Boolean(), nullable=True),
        sa.Column('split_expense_added', sa.Boolean(), nullable=True),
        sa.Column('split_expense_updated', sa.Boolean(), nullable=True),
        sa.Column('split_settlement', sa.Boolean(), nullable=True),
        sa.Column('split_group_activity', sa.Boolean(), nullable=True),
        sa.Column('split_friend_activity', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
        op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    if not _has_table('notifications'):
        op.create_table('notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('body', sa.String(), nullable=True),
        sa.Column('link_type', sa.String(), nullable=True),
        sa.Column('link_id', sa.String(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
        op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
        op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
        op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
        op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    if not _has_table('split_persons'):
        op.create_table('split_persons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('avatar_color', sa.String(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('claimed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_split_persons_created_by_user_id'), 'split_persons', ['created_by_user_id'], unique=False)
        op.create_index(op.f('ix_split_persons_email'), 'split_persons', ['email'], unique=True)
        op.create_index(op.f('ix_split_persons_id'), 'split_persons', ['id'], unique=False)
        op.create_index(op.f('ix_split_persons_phone'), 'split_persons', ['phone'], unique=False)
        op.create_index(op.f('ix_split_persons_user_id'), 'split_persons', ['user_id'], unique=True)
    if not _has_table('subscriptions'):
        op.create_table('subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('plan', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
        op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    if not _has_table('budget_goals'):
        op.create_table('budget_goals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('profile_id', sa.Integer(), nullable=True),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('monthly_limit', sa.Float(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('last_alerted_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_budget_goals_id'), 'budget_goals', ['id'], unique=False)
        op.create_index(op.f('ix_budget_goals_profile_id'), 'budget_goals', ['profile_id'], unique=False)
    if not _has_table('experience_badges'):
        op.create_table('experience_badges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('profile_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('icon', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('earned_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_experience_badges_id'), 'experience_badges', ['id'], unique=False)
        op.create_index(op.f('ix_experience_badges_profile_id'), 'experience_badges', ['profile_id'], unique=False)
    if not _has_table('shared_goals'):
        op.create_table('shared_goals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_profile_id', sa.Integer(), nullable=True),
        sa.Column('goal_data', sa.JSON(), nullable=True),
        sa.Column('participants', sa.JSON(), nullable=True),
        sa.Column('split_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['owner_profile_id'], ['profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_shared_goals_id'), 'shared_goals', ['id'], unique=False)
        op.create_index(op.f('ix_shared_goals_owner_profile_id'), 'shared_goals', ['owner_profile_id'], unique=False)
    if not _has_table('split_friendships'):
        op.create_table('split_friendships',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('person_a_id', sa.Integer(), nullable=False),
        sa.Column('person_b_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('requested_by_person_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['person_a_id'], ['split_persons.id'], ),
        sa.ForeignKeyConstraint(['person_b_id'], ['split_persons.id'], ),
        sa.ForeignKeyConstraint(['requested_by_person_id'], ['split_persons.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('person_a_id', 'person_b_id', name='uq_split_friend_pair')
        )
        op.create_index(op.f('ix_split_friendships_id'), 'split_friendships', ['id'], unique=False)
        op.create_index(op.f('ix_split_friendships_person_a_id'), 'split_friendships', ['person_a_id'], unique=False)
        op.create_index(op.f('ix_split_friendships_person_b_id'), 'split_friendships', ['person_b_id'], unique=False)
    if not _has_table('split_groups'):
        op.create_table('split_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('group_type', sa.String(), nullable=True),
        sa.Column('emoji', sa.String(), nullable=True),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('created_by_person_id', sa.Integer(), nullable=False),
        sa.Column('simplify_debts', sa.Boolean(), nullable=True),
        sa.Column('is_archived', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_person_id'], ['split_persons.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_split_groups_created_by_person_id'), 'split_groups', ['created_by_person_id'], unique=False)
        op.create_index(op.f('ix_split_groups_id'), 'split_groups', ['id'], unique=False)
    if not _has_table('split_expenses'):
        op.create_table('split_expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('total_minor', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('expense_date', sa.Date(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('receipt_url', sa.String(), nullable=True),
        sa.Column('split_mode', sa.String(), nullable=True),
        sa.Column('created_by_person_id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('client_token', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_person_id'], ['split_persons.id'], ),
        sa.ForeignKeyConstraint(['group_id'], ['split_groups.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_split_expenses_client_token'), 'split_expenses', ['client_token'], unique=True)
        op.create_index(op.f('ix_split_expenses_created_by_person_id'), 'split_expenses', ['created_by_person_id'], unique=False)
        op.create_index(op.f('ix_split_expenses_expense_date'), 'split_expenses', ['expense_date'], unique=False)
        op.create_index(op.f('ix_split_expenses_group_id'), 'split_expenses', ['group_id'], unique=False)
        op.create_index(op.f('ix_split_expenses_id'), 'split_expenses', ['id'], unique=False)
        op.create_index(op.f('ix_split_expenses_is_deleted'), 'split_expenses', ['is_deleted'], unique=False)
    if not _has_table('split_group_members'):
        op.create_table('split_group_members',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('joined_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['split_groups.id'], ),
        sa.ForeignKeyConstraint(['person_id'], ['split_persons.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('group_id', 'person_id', name='uq_split_group_member')
        )
        op.create_index(op.f('ix_split_group_members_group_id'), 'split_group_members', ['group_id'], unique=False)
        op.create_index(op.f('ix_split_group_members_id'), 'split_group_members', ['id'], unique=False)
        op.create_index(op.f('ix_split_group_members_person_id'), 'split_group_members', ['person_id'], unique=False)
    if not _has_table('split_invitations'):
        op.create_table('split_invitations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('invited_by_person_id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('accepted_by_user_id', sa.Integer(), nullable=True),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['group_id'], ['split_groups.id'], ),
        sa.ForeignKeyConstraint(['invited_by_person_id'], ['split_persons.id'], ),
        sa.ForeignKeyConstraint(['person_id'], ['split_persons.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_split_invitations_email'), 'split_invitations', ['email'], unique=False)
        op.create_index(op.f('ix_split_invitations_group_id'), 'split_invitations', ['group_id'], unique=False)
        op.create_index(op.f('ix_split_invitations_id'), 'split_invitations', ['id'], unique=False)
        op.create_index(op.f('ix_split_invitations_invited_by_person_id'), 'split_invitations', ['invited_by_person_id'], unique=False)
        op.create_index(op.f('ix_split_invitations_person_id'), 'split_invitations', ['person_id'], unique=False)
        op.create_index(op.f('ix_split_invitations_token'), 'split_invitations', ['token'], unique=True)
    if not _has_table('split_settlements'):
        op.create_table('split_settlements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('from_person_id', sa.Integer(), nullable=False),
        sa.Column('to_person_id', sa.Integer(), nullable=False),
        sa.Column('amount_minor', sa.Integer(), nullable=False),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('method', sa.String(), nullable=True),
        sa.Column('note', sa.String(), nullable=True),
        sa.Column('settled_on', sa.Date(), nullable=True),
        sa.Column('recorded_by_person_id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('client_token', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['from_person_id'], ['split_persons.id'], ),
        sa.ForeignKeyConstraint(['group_id'], ['split_groups.id'], ),
        sa.ForeignKeyConstraint(['recorded_by_person_id'], ['split_persons.id'], ),
        sa.ForeignKeyConstraint(['to_person_id'], ['split_persons.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_split_settlements_client_token'), 'split_settlements', ['client_token'], unique=True)
        op.create_index(op.f('ix_split_settlements_from_person_id'), 'split_settlements', ['from_person_id'], unique=False)
        op.create_index(op.f('ix_split_settlements_group_id'), 'split_settlements', ['group_id'], unique=False)
        op.create_index(op.f('ix_split_settlements_id'), 'split_settlements', ['id'], unique=False)
        op.create_index(op.f('ix_split_settlements_is_deleted'), 'split_settlements', ['is_deleted'], unique=False)
        op.create_index(op.f('ix_split_settlements_settled_on'), 'split_settlements', ['settled_on'], unique=False)
        op.create_index(op.f('ix_split_settlements_to_person_id'), 'split_settlements', ['to_person_id'], unique=False)
    if not _has_table('split_activities'):
        op.create_table('split_activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.String(), nullable=False),
        sa.Column('actor_person_id', sa.Integer(), nullable=False),
        sa.Column('actor_name', sa.String(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('expense_id', sa.Integer(), nullable=True),
        sa.Column('settlement_id', sa.Integer(), nullable=True),
        sa.Column('summary', sa.String(), nullable=False),
        sa.Column('amount_minor', sa.Integer(), nullable=True),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('audience_person_ids', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['actor_person_id'], ['split_persons.id'], ),
        sa.ForeignKeyConstraint(['expense_id'], ['split_expenses.id'], ),
        sa.ForeignKeyConstraint(['group_id'], ['split_groups.id'], ),
        sa.ForeignKeyConstraint(['settlement_id'], ['split_settlements.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_split_activities_actor_person_id'), 'split_activities', ['actor_person_id'], unique=False)
        op.create_index(op.f('ix_split_activities_created_at'), 'split_activities', ['created_at'], unique=False)
        op.create_index(op.f('ix_split_activities_expense_id'), 'split_activities', ['expense_id'], unique=False)
        op.create_index(op.f('ix_split_activities_group_id'), 'split_activities', ['group_id'], unique=False)
        op.create_index(op.f('ix_split_activities_id'), 'split_activities', ['id'], unique=False)
        op.create_index(op.f('ix_split_activities_kind'), 'split_activities', ['kind'], unique=False)
        op.create_index(op.f('ix_split_activities_settlement_id'), 'split_activities', ['settlement_id'], unique=False)
    if not _has_table('split_expense_items'):
        op.create_table('split_expense_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('expense_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('amount_minor', sa.Integer(), nullable=False),
        sa.Column('participant_person_ids', sa.JSON(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['expense_id'], ['split_expenses.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_split_expense_items_expense_id'), 'split_expense_items', ['expense_id'], unique=False)
        op.create_index(op.f('ix_split_expense_items_id'), 'split_expense_items', ['id'], unique=False)
    if not _has_table('split_expense_payers'):
        op.create_table('split_expense_payers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('expense_id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column('amount_minor', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['expense_id'], ['split_expenses.id'], ),
        sa.ForeignKeyConstraint(['person_id'], ['split_persons.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('expense_id', 'person_id', name='uq_split_expense_payer')
        )
        op.create_index(op.f('ix_split_expense_payers_expense_id'), 'split_expense_payers', ['expense_id'], unique=False)
        op.create_index(op.f('ix_split_expense_payers_id'), 'split_expense_payers', ['id'], unique=False)
        op.create_index(op.f('ix_split_expense_payers_person_id'), 'split_expense_payers', ['person_id'], unique=False)
    if not _has_table('split_expense_shares'):
        op.create_table('split_expense_shares',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('expense_id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column('share_minor', sa.Integer(), nullable=False),
        sa.Column('weight', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['expense_id'], ['split_expenses.id'], ),
        sa.ForeignKeyConstraint(['person_id'], ['split_persons.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('expense_id', 'person_id', name='uq_split_expense_share')
        )
        op.create_index(op.f('ix_split_expense_shares_expense_id'), 'split_expense_shares', ['expense_id'], unique=False)
        op.create_index(op.f('ix_split_expense_shares_id'), 'split_expense_shares', ['id'], unique=False)
        op.create_index(op.f('ix_split_expense_shares_person_id'), 'split_expense_shares', ['person_id'], unique=False)
        op.drop_constraint(op.f('startup_profiles_profile_id_key'), 'startup_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('startup_profiles_profile_id_key'), 'startup_profiles', ['profile_id'])
    if _has_table('split_expense_shares'):
        op.drop_index(op.f('ix_split_expense_shares_person_id'), table_name='split_expense_shares')
    if _has_table('split_expense_shares'):
        op.drop_index(op.f('ix_split_expense_shares_id'), table_name='split_expense_shares')
    if _has_table('split_expense_shares'):
        op.drop_index(op.f('ix_split_expense_shares_expense_id'), table_name='split_expense_shares')
    if _has_table('split_expense_shares'):
        op.drop_table('split_expense_shares')
    if _has_table('split_expense_payers'):
        op.drop_index(op.f('ix_split_expense_payers_person_id'), table_name='split_expense_payers')
    if _has_table('split_expense_payers'):
        op.drop_index(op.f('ix_split_expense_payers_id'), table_name='split_expense_payers')
    if _has_table('split_expense_payers'):
        op.drop_index(op.f('ix_split_expense_payers_expense_id'), table_name='split_expense_payers')
    if _has_table('split_expense_payers'):
        op.drop_table('split_expense_payers')
    if _has_table('split_expense_items'):
        op.drop_index(op.f('ix_split_expense_items_id'), table_name='split_expense_items')
    if _has_table('split_expense_items'):
        op.drop_index(op.f('ix_split_expense_items_expense_id'), table_name='split_expense_items')
    if _has_table('split_expense_items'):
        op.drop_table('split_expense_items')
    if _has_table('split_activities'):
        op.drop_index(op.f('ix_split_activities_settlement_id'), table_name='split_activities')
    if _has_table('split_activities'):
        op.drop_index(op.f('ix_split_activities_kind'), table_name='split_activities')
    if _has_table('split_activities'):
        op.drop_index(op.f('ix_split_activities_id'), table_name='split_activities')
    if _has_table('split_activities'):
        op.drop_index(op.f('ix_split_activities_group_id'), table_name='split_activities')
    if _has_table('split_activities'):
        op.drop_index(op.f('ix_split_activities_expense_id'), table_name='split_activities')
    if _has_table('split_activities'):
        op.drop_index(op.f('ix_split_activities_created_at'), table_name='split_activities')
    if _has_table('split_activities'):
        op.drop_index(op.f('ix_split_activities_actor_person_id'), table_name='split_activities')
    if _has_table('split_activities'):
        op.drop_table('split_activities')
    if _has_table('split_settlements'):
        op.drop_index(op.f('ix_split_settlements_to_person_id'), table_name='split_settlements')
    if _has_table('split_settlements'):
        op.drop_index(op.f('ix_split_settlements_settled_on'), table_name='split_settlements')
    if _has_table('split_settlements'):
        op.drop_index(op.f('ix_split_settlements_is_deleted'), table_name='split_settlements')
    if _has_table('split_settlements'):
        op.drop_index(op.f('ix_split_settlements_id'), table_name='split_settlements')
    if _has_table('split_settlements'):
        op.drop_index(op.f('ix_split_settlements_group_id'), table_name='split_settlements')
    if _has_table('split_settlements'):
        op.drop_index(op.f('ix_split_settlements_from_person_id'), table_name='split_settlements')
    if _has_table('split_settlements'):
        op.drop_index(op.f('ix_split_settlements_client_token'), table_name='split_settlements')
    if _has_table('split_settlements'):
        op.drop_table('split_settlements')
    if _has_table('split_invitations'):
        op.drop_index(op.f('ix_split_invitations_token'), table_name='split_invitations')
    if _has_table('split_invitations'):
        op.drop_index(op.f('ix_split_invitations_person_id'), table_name='split_invitations')
    if _has_table('split_invitations'):
        op.drop_index(op.f('ix_split_invitations_invited_by_person_id'), table_name='split_invitations')
    if _has_table('split_invitations'):
        op.drop_index(op.f('ix_split_invitations_id'), table_name='split_invitations')
    if _has_table('split_invitations'):
        op.drop_index(op.f('ix_split_invitations_group_id'), table_name='split_invitations')
    if _has_table('split_invitations'):
        op.drop_index(op.f('ix_split_invitations_email'), table_name='split_invitations')
    if _has_table('split_invitations'):
        op.drop_table('split_invitations')
    if _has_table('split_group_members'):
        op.drop_index(op.f('ix_split_group_members_person_id'), table_name='split_group_members')
    if _has_table('split_group_members'):
        op.drop_index(op.f('ix_split_group_members_id'), table_name='split_group_members')
    if _has_table('split_group_members'):
        op.drop_index(op.f('ix_split_group_members_group_id'), table_name='split_group_members')
    if _has_table('split_group_members'):
        op.drop_table('split_group_members')
    if _has_table('split_expenses'):
        op.drop_index(op.f('ix_split_expenses_is_deleted'), table_name='split_expenses')
    if _has_table('split_expenses'):
        op.drop_index(op.f('ix_split_expenses_id'), table_name='split_expenses')
    if _has_table('split_expenses'):
        op.drop_index(op.f('ix_split_expenses_group_id'), table_name='split_expenses')
    if _has_table('split_expenses'):
        op.drop_index(op.f('ix_split_expenses_expense_date'), table_name='split_expenses')
    if _has_table('split_expenses'):
        op.drop_index(op.f('ix_split_expenses_created_by_person_id'), table_name='split_expenses')
    if _has_table('split_expenses'):
        op.drop_index(op.f('ix_split_expenses_client_token'), table_name='split_expenses')
    if _has_table('split_expenses'):
        op.drop_table('split_expenses')
    if _has_table('split_groups'):
        op.drop_index(op.f('ix_split_groups_id'), table_name='split_groups')
    if _has_table('split_groups'):
        op.drop_index(op.f('ix_split_groups_created_by_person_id'), table_name='split_groups')
    if _has_table('split_groups'):
        op.drop_table('split_groups')
    if _has_table('split_friendships'):
        op.drop_index(op.f('ix_split_friendships_person_b_id'), table_name='split_friendships')
    if _has_table('split_friendships'):
        op.drop_index(op.f('ix_split_friendships_person_a_id'), table_name='split_friendships')
    if _has_table('split_friendships'):
        op.drop_index(op.f('ix_split_friendships_id'), table_name='split_friendships')
    if _has_table('split_friendships'):
        op.drop_table('split_friendships')
    if _has_table('shared_goals'):
        op.drop_index(op.f('ix_shared_goals_owner_profile_id'), table_name='shared_goals')
    if _has_table('shared_goals'):
        op.drop_index(op.f('ix_shared_goals_id'), table_name='shared_goals')
    if _has_table('shared_goals'):
        op.drop_table('shared_goals')
    if _has_table('experience_badges'):
        op.drop_index(op.f('ix_experience_badges_profile_id'), table_name='experience_badges')
    if _has_table('experience_badges'):
        op.drop_index(op.f('ix_experience_badges_id'), table_name='experience_badges')
    if _has_table('experience_badges'):
        op.drop_table('experience_badges')
    if _has_table('budget_goals'):
        op.drop_index(op.f('ix_budget_goals_profile_id'), table_name='budget_goals')
    if _has_table('budget_goals'):
        op.drop_index(op.f('ix_budget_goals_id'), table_name='budget_goals')
    if _has_table('budget_goals'):
        op.drop_table('budget_goals')
    if _has_table('subscriptions'):
        op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    if _has_table('subscriptions'):
        op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    if _has_table('subscriptions'):
        op.drop_table('subscriptions')
    if _has_table('split_persons'):
        op.drop_index(op.f('ix_split_persons_user_id'), table_name='split_persons')
    if _has_table('split_persons'):
        op.drop_index(op.f('ix_split_persons_phone'), table_name='split_persons')
    if _has_table('split_persons'):
        op.drop_index(op.f('ix_split_persons_id'), table_name='split_persons')
    if _has_table('split_persons'):
        op.drop_index(op.f('ix_split_persons_email'), table_name='split_persons')
    if _has_table('split_persons'):
        op.drop_index(op.f('ix_split_persons_created_by_user_id'), table_name='split_persons')
    if _has_table('split_persons'):
        op.drop_table('split_persons')
    if _has_table('notifications'):
        op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    if _has_table('notifications'):
        op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    if _has_table('notifications'):
        op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    if _has_table('notifications'):
        op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    if _has_table('notifications'):
        op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    if _has_table('notifications'):
        op.drop_table('notifications')
    if _has_table('notification_preferences'):
        op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    if _has_table('notification_preferences'):
        op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    if _has_table('notification_preferences'):
        op.drop_table('notification_preferences')
    # ### end Alembic commands ###
