"""add gmail connections

Revision ID: 54c4d08832d8
Revises: c8d2e4f6a7b9
Create Date: 2026-08-23 16:09:35.413097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c4d08832d8'
down_revision: Union[str, Sequence[str], None] = 'c8d2e4f6a7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_history_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_connections_id'), 'gmail_connections', ['id'], unique=False)
    op.create_index(op.f('ix_gmail_connections_profile_id'), 'gmail_connections', ['profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_connections_profile_id'), table_name='gmail_connections')
    op.drop_index(op.f('ix_gmail_connections_id'), table_name='gmail_connections')
    op.drop_table('gmail_connections')
    # ### end Alembic commands ###
