"""allow_multiple_gmail_connections

Revision ID: 8bfb32224221
Revises: 7d3d78c3ca00
Create Date: 2026-08-26 23:05:03.954336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfb32224221'
down_revision: Union[str, Sequence[str], None] = '7d3d78c3ca00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_connections_profile_id'), table_name='gmail_connections')
    op.create_index(op.f('ix_gmail_connections_profile_id'), 'gmail_connections', ['profile_id'], unique=False)
    # SQLite has no ALTER COLUMN, and it stores JSON as TEXT regardless, so the
    # type change is a no-op there. Other dialects still get the real ALTER.
    if op.get_bind().dialect.name != 'sqlite':
        op.alter_column('profiles', 'raw_inputs',
                   existing_type=sa.TEXT(),
                   type_=sa.JSON(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != 'sqlite':
        op.alter_column('profiles', 'raw_inputs',
                   existing_type=sa.JSON(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    op.drop_index(op.f('ix_gmail_connections_profile_id'), table_name='gmail_connections')
    op.create_index(op.f('ix_gmail_connections_profile_id'), 'gmail_connections', ['profile_id'], unique=1)
    # ### end Alembic commands ###
