"""Add auto_sweep_enabled to Profile

Revision ID: 9f43d189dd4c
Revises: 73e3beff3547
Create Date: 2026-09-03 14:34:33.359667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f43d189dd4c'
down_revision: Union[str, Sequence[str], None] = '73e3beff3547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Idempotence guards.
#
# This revision was generated by autogenerate against a database whose schema
# had drifted from the migration history: `whatsapp_connections` had been
# created there by the old unconditional `Base.metadata.create_all()` and never
# by any migration, so autogenerate emitted a DROP for a table no migration had
# ever built. It also re-adds three columns that the hand-written revisions on
# the parallel branch (c4f1a8b02d17, d5c2e9a71f34) already add, and after the
# branches merged both ends up in the same chain.
#
# The result was that `alembic upgrade head` could not build a database from
# empty — which is only invisible while every existing database is already at
# head. A new environment, a new teammate's machine or a hosted database is
# exactly where it surfaces.
#
# These guards make each step a no-op where it has already happened. Nothing
# about the intended end state changes, and on a database that is already at
# head nothing here runs at all.
# ---------------------------------------------------------------------------

def _has_table(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _has_column(table: str, column: str) -> bool:
    insp = sa.inspect(op.get_bind())
    if not insp.has_table(table):
        return False
    return column in {c["name"] for c in insp.get_columns(table)}



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_table('whatsapp_connections'):
        op.drop_index(op.f('ix_whatsapp_connections_id'), table_name='whatsapp_connections')
        op.drop_index(op.f('ix_whatsapp_connections_instance_name'), table_name='whatsapp_connections')
        op.drop_index(op.f('ix_whatsapp_connections_profile_id'), table_name='whatsapp_connections')
        op.drop_table('whatsapp_connections')
    if not _has_column('financial_goals', 'shared_with_profile_ids'):
        op.add_column('financial_goals', sa.Column('shared_with_profile_ids', sa.JSON(), nullable=True))
    if not _has_column('profiles', 'auto_sweep_enabled'):
        op.add_column('profiles', sa.Column('auto_sweep_enabled', sa.Boolean(), nullable=True))
    if not _has_column('profiles', 'sweep_rules'):
        op.add_column('profiles', sa.Column('sweep_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_column('profiles', 'sweep_rules'):
        op.drop_column('profiles', 'sweep_rules')
    if _has_column('profiles', 'auto_sweep_enabled'):
        op.drop_column('profiles', 'auto_sweep_enabled')
    if _has_column('financial_goals', 'shared_with_profile_ids'):
        op.drop_column('financial_goals', 'shared_with_profile_ids')
    if _has_table('whatsapp_connections'):
        return
    op.create_table('whatsapp_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('instance_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('connected_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_connected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_alert_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('whatsapp_connections_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('whatsapp_connections_pkey'))
    )
    op.create_index(op.f('ix_whatsapp_connections_profile_id'), 'whatsapp_connections', ['profile_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_connections_instance_name'), 'whatsapp_connections', ['instance_name'], unique=True)
    op.create_index(op.f('ix_whatsapp_connections_id'), 'whatsapp_connections', ['id'], unique=False)
    # ### end Alembic commands ###
