"""add_insights_schedule

Revision ID: ec8170c8e88e
Revises: 5e21ca5bcc7b
Create Date: 2026-09-06 18:21:11.288729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8170c8e88e'
down_revision: Union[str, Sequence[str], None] = '5e21ca5bcc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('insights_schedule', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('whatsapp_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'whatsapp_phone')
    op.drop_column('profiles', 'insights_schedule')
    # ### end Alembic commands ###
